-- Catálogo global de ejercicios organizado por categoría (28 categorías).
-- Los 3 ejercicios (DEMO) ya existentes se REUTILIZAN: se renombran y
-- categorizan en lugar de insertarse duplicados (ver UPDATE al inicio).
-- Todo lo demás se inserta como ejercicio global (gym_id NULL), disponible
-- para todos los gimnasios y protegido contra edición/desactivación desde
-- cualquier gimnasio individual (la aplicación ya impone esto mediante
-- WHERE gym_id = $gymId en updateExercise/setExerciseStatus).

ALTER TABLE exercises ADD COLUMN category TEXT;
CREATE INDEX idx_exercises_gym_category ON exercises (gym_id, category);

-- Reutilización de ejercicios existentes (no se duplican)
UPDATE exercises SET name = 'Press de banca plano con barra', category = 'Pecho', muscle_group = 'CHEST', exercise_type = 'STRENGTH', equipment = 'Barra', updated_at = datetime('now') WHERE id = 'exercise_demo_001';
UPDATE exercises SET name = 'Peso muerto convencional', category = 'Espalda', muscle_group = 'BACK', exercise_type = 'STRENGTH', equipment = 'Barra', updated_at = datetime('now') WHERE id = 'exercise_demo_003';
UPDATE exercises SET name = 'Sentadilla trasera', category = 'Cuádriceps', muscle_group = 'QUADRICEPS', exercise_type = 'STRENGTH', equipment = 'Barra', updated_at = datetime('now') WHERE id = 'exercise_demo_002';

-- Catálogo nuevo (ejercicios globales)
INSERT INTO exercises (id, gym_id, name, category, muscle_group, exercise_type, equipment, level, status)
VALUES
('exercise_glob_0001', NULL, 'Press de banca inclinado con barra', 'Pecho', 'CHEST', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0002', NULL, 'Press de banca declinado con barra', 'Pecho', 'CHEST', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0003', NULL, 'Press cerrado con barra', 'Pecho', 'CHEST', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0004', NULL, 'Press Spoto', 'Pecho', 'CHEST', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0005', NULL, 'Press con pausa', 'Pecho', 'CHEST', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0006', NULL, 'Press con agarre amplio', 'Pecho', 'CHEST', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0007', NULL, 'Press plano con mancuernas', 'Pecho', 'CHEST', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0008', NULL, 'Press inclinado con mancuernas', 'Pecho', 'CHEST', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0009', NULL, 'Press declinado con mancuernas', 'Pecho', 'CHEST', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0010', NULL, 'Press neutro con mancuernas', 'Pecho', 'CHEST', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0011', NULL, 'Press alternado con mancuernas', 'Pecho', 'CHEST', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0012', NULL, 'Aperturas planas con mancuernas', 'Pecho', 'CHEST', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0013', NULL, 'Aperturas inclinadas con mancuernas', 'Pecho', 'CHEST', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0014', NULL, 'Squeeze Press', 'Pecho', 'CHEST', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0015', NULL, 'Press de pecho en máquina', 'Pecho', 'CHEST', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0016', NULL, 'Press inclinado en máquina', 'Pecho', 'CHEST', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0017', NULL, 'Press convergente', 'Pecho', 'CHEST', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0018', NULL, 'Press horizontal en máquina', 'Pecho', 'CHEST', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0019', NULL, 'Pec Deck', 'Pecho', 'CHEST', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0020', NULL, 'Chest Press Hammer', 'Pecho', 'CHEST', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0021', NULL, 'Press unilateral en máquina', 'Pecho', 'CHEST', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0022', NULL, 'Cruce de poleas alto', 'Pecho', 'CHEST', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0023', NULL, 'Cruce de poleas medio', 'Pecho', 'CHEST', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0024', NULL, 'Cruce de poleas bajo', 'Pecho', 'CHEST', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0025', NULL, 'Aperturas con poleas', 'Pecho', 'CHEST', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0026', NULL, 'Press de pecho en polea', 'Pecho', 'CHEST', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0027', NULL, 'Press unilateral en polea', 'Pecho', 'CHEST', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0028', NULL, 'Flexiones', 'Pecho', 'CHEST', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0029', NULL, 'Flexiones inclinadas', 'Pecho', 'CHEST', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0030', NULL, 'Flexiones declinadas', 'Pecho', 'CHEST', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0031', NULL, 'Flexiones diamante', 'Pecho', 'CHEST', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0032', NULL, 'Flexiones abiertas', 'Pecho', 'CHEST', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0033', NULL, 'Flexiones explosivas', 'Pecho', 'CHEST', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0034', NULL, 'Flexiones con pausa', 'Pecho', 'CHEST', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0035', NULL, 'Fondos para pecho', 'Pecho', 'CHEST', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0036', NULL, 'Dominadas', 'Espalda', 'BACK', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0037', NULL, 'Dominadas pronas', 'Espalda', 'BACK', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0038', NULL, 'Dominadas supinas', 'Espalda', 'BACK', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0039', NULL, 'Dominadas neutras', 'Espalda', 'BACK', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0040', NULL, 'Remo con barra', 'Espalda', 'BACK', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0041', NULL, 'Remo Pendlay', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0042', NULL, 'Remo T-Bar', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0043', NULL, 'Remo con barra agarre supino', 'Espalda', 'BACK', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0044', NULL, 'Peso muerto sumo', 'Espalda', 'BACK', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0045', NULL, 'Peso muerto rumano', 'Espalda', 'BACK', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0046', NULL, 'Remo con mancuerna', 'Espalda', 'BACK', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0047', NULL, 'Remo unilateral', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0048', NULL, 'Remo con dos mancuernas', 'Espalda', 'BACK', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0049', NULL, 'Remo pecho apoyado', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0050', NULL, 'Pullover con mancuerna', 'Espalda', 'BACK', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0051', NULL, 'Jalón en máquina', 'Espalda', 'BACK', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0052', NULL, 'Remo sentado en máquina', 'Espalda', 'BACK', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0053', NULL, 'Remo Hammer', 'Espalda', 'BACK', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0054', NULL, 'Remo unilateral en máquina', 'Espalda', 'BACK', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0055', NULL, 'High Row', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0056', NULL, 'Low Row', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0057', NULL, 'Pullover en máquina', 'Espalda', 'BACK', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0058', NULL, 'Máquina de dominadas asistidas', 'Espalda', 'BACK', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0059', NULL, 'Jalón al pecho', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0060', NULL, 'Jalón agarre amplio', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0061', NULL, 'Jalón agarre cerrado', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0062', NULL, 'Jalón agarre neutro', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0063', NULL, 'Jalón unilateral', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0064', NULL, 'Remo sentado', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0065', NULL, 'Remo bajo', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0066', NULL, 'Remo unilateral en polea', 'Espalda', 'BACK', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0067', NULL, 'Pullover en polea', 'Espalda', 'BACK', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0068', NULL, 'Face Pull', 'Espalda', 'BACK', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0069', NULL, 'Curl alternado con mancuernas', 'Bíceps', 'BICEPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0070', NULL, 'Curl simultáneo con mancuernas', 'Bíceps', 'BICEPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0071', NULL, 'Curl martillo', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0072', NULL, 'Curl martillo cruzado', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0073', NULL, 'Curl concentrado', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0074', NULL, 'Curl inclinado', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0075', NULL, 'Curl sentado', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0076', NULL, 'Curl supino', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0077', NULL, 'Curl Zottman', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0078', NULL, 'Curl araña', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0079', NULL, 'Curl con barra recta', 'Bíceps', 'BICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0080', NULL, 'Curl con barra EZ', 'Bíceps', 'BICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0081', NULL, 'Curl predicador con barra', 'Bíceps', 'BICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0082', NULL, 'Curl inverso', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0083', NULL, 'Curl agarre cerrado', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0084', NULL, 'Curl agarre amplio', 'Bíceps', 'BICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0085', NULL, 'Curl en polea baja', 'Bíceps', 'BICEPS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0086', NULL, 'Curl unilateral en polea', 'Bíceps', 'BICEPS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0087', NULL, 'Curl martillo en polea', 'Bíceps', 'BICEPS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0088', NULL, 'Curl predicador en polea', 'Bíceps', 'BICEPS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0089', NULL, 'Curl con cuerda', 'Bíceps', 'BICEPS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0090', NULL, 'Curl doble en polea', 'Bíceps', 'BICEPS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0091', NULL, 'Curl predicador en máquina', 'Bíceps', 'BICEPS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0092', NULL, 'Curl de bíceps en máquina', 'Bíceps', 'BICEPS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0093', NULL, 'Extensión de tríceps con cuerda', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0094', NULL, 'Extensión con barra', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0095', NULL, 'Extensión unilateral', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0096', NULL, 'Extensión por encima de la cabeza', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0097', NULL, 'Extensión con cuerda sobre cabeza', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0098', NULL, 'Pushdown', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0099', NULL, 'Pushdown unilateral', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0100', NULL, 'Pushdown agarre inverso', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0101', NULL, 'Extensión sobre cabeza con mancuerna', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0102', NULL, 'Extensión unilateral con mancuerna', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0103', NULL, 'Patada de tríceps', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0104', NULL, 'Press francés con mancuernas', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0105', NULL, 'Press cerrado con mancuernas', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0106', NULL, 'Press francés con barra', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0107', NULL, 'Press cerrado inclinado', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0108', NULL, 'Rompecráneos', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0109', NULL, 'Fondos en paralelas', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0110', NULL, 'Fondos en banco', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Banco', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0111', NULL, 'Tríceps en máquina', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0112', NULL, 'Fondos asistidos', 'Tríceps', 'TRICEPS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0113', NULL, 'Press militar con mancuernas', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0114', NULL, 'Press Arnold', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0115', NULL, 'Elevaciones laterales', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0116', NULL, 'Elevaciones frontales', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0117', NULL, 'Elevaciones posteriores', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0118', NULL, 'Pájaros', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0119', NULL, 'Press sentado', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0120', NULL, 'Press unilateral', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0121', NULL, 'Elevación lateral unilateral', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0122', NULL, 'Press militar con barra', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0123', NULL, 'Press tras nuca', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0124', NULL, 'Push Press', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0125', NULL, 'Press Bradford', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0126', NULL, 'Remo al mentón', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0127', NULL, 'Elevación lateral en polea', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0128', NULL, 'Elevación frontal en polea', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0129', NULL, 'Elevación posterior en polea', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0130', NULL, 'Press de hombros en máquina', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0131', NULL, 'Elevación lateral en máquina', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0132', NULL, 'Reverse Pec Deck', 'Hombros', 'SHOULDERS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0133', NULL, 'Sentadilla frontal', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0134', NULL, 'Sentadilla Zercher', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0135', NULL, 'Sentadilla Hack con barra', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0136', NULL, 'Zancadas con barra', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0137', NULL, 'Split Squat con barra', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0138', NULL, 'Sentadilla con mancuernas', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0139', NULL, 'Zancadas con mancuernas', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0140', NULL, 'Zancadas caminando', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0141', NULL, 'Zancadas inversas', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0142', NULL, 'Bulgarian Split Squat', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0143', NULL, 'Step Up', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0144', NULL, 'Goblet Squat', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0145', NULL, 'Prensa de piernas', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0146', NULL, 'Hack Squat', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0147', NULL, 'Extensión de piernas', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0148', NULL, 'Sentadilla pendular', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0149', NULL, 'Belt Squat', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0150', NULL, 'V-Squat', 'Cuádriceps', 'QUADRICEPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0151', NULL, 'Hip Thrust con barra', 'Glúteos', 'GLUTES', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0152', NULL, 'Glute Bridge con barra', 'Glúteos', 'GLUTES', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0153', NULL, 'Sentadilla profunda', 'Glúteos', 'GLUTES', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0154', NULL, 'Sentadilla sumo', 'Glúteos', 'GLUTES', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0155', NULL, 'Buenos días', 'Glúteos', 'GLUTES', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0156', NULL, 'Hip Thrust con mancuerna', 'Glúteos', 'GLUTES', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0157', NULL, 'Glute Bridge con mancuerna', 'Glúteos', 'GLUTES', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0158', NULL, 'Zancada larga', 'Glúteos', 'GLUTES', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0159', NULL, 'Peso muerto rumano con mancuernas', 'Glúteos', 'GLUTES', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0160', NULL, 'Hip Thrust en máquina', 'Glúteos', 'GLUTES', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0161', NULL, 'Máquina de glúteo', 'Glúteos', 'GLUTES', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0162', NULL, 'Patada de glúteo en máquina', 'Glúteos', 'GLUTES', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0163', NULL, 'Abducción de cadera', 'Glúteos', 'GLUTES', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0164', NULL, 'Prensa inclinada', 'Glúteos', 'GLUTES', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0165', NULL, 'Patada de glúteo en polea', 'Glúteos', 'GLUTES', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0166', NULL, 'Abducción en polea', 'Glúteos', 'GLUTES', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0167', NULL, 'Extensión de cadera en polea', 'Glúteos', 'GLUTES', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0168', NULL, 'Peso muerto piernas rígidas', 'Femorales', 'HAMSTRINGS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0169', NULL, 'Curl femoral tumbado', 'Femorales', 'HAMSTRINGS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0170', NULL, 'Curl femoral sentado', 'Femorales', 'HAMSTRINGS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0171', NULL, 'Curl femoral de pie', 'Femorales', 'HAMSTRINGS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0172', NULL, 'Nordic Curl', 'Femorales', 'HAMSTRINGS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0173', NULL, 'Glute Ham Raise', 'Femorales', 'HAMSTRINGS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0174', NULL, 'Peso muerto unilateral', 'Femorales', 'HAMSTRINGS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0175', NULL, 'Buenos días en máquina', 'Femorales', 'HAMSTRINGS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0176', NULL, 'Elevación de talones de pie', 'Pantorrillas', 'CALVES', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0177', NULL, 'Elevación de talones sentado', 'Pantorrillas', 'CALVES', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0178', NULL, 'Elevación de talones en prensa', 'Pantorrillas', 'CALVES', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0179', NULL, 'Elevación unilateral', 'Pantorrillas', 'CALVES', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0180', NULL, 'Donkey Calf Raise', 'Pantorrillas', 'CALVES', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0181', NULL, 'Calf Raise en máquina', 'Pantorrillas', 'CALVES', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0182', NULL, 'Calf Raise en Smith', 'Pantorrillas', 'CALVES', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0183', NULL, 'Calf Raise con mancuernas', 'Pantorrillas', 'CALVES', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0184', NULL, 'Crunch', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0185', NULL, 'Crunch en máquina', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0186', NULL, 'Crunch en polea', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0187', NULL, 'Crunch con cuerda', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0188', NULL, 'Sit Up', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0189', NULL, 'Reverse Crunch', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0190', NULL, 'Elevación de piernas', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0191', NULL, 'Elevación de rodillas', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0192', NULL, 'Elevación de piernas colgado', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0193', NULL, 'Ab Wheel', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0194', NULL, 'Plancha', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0195', NULL, 'Plancha lateral', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0196', NULL, 'Plancha con apoyo de antebrazos', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0197', NULL, 'Plancha con peso', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0198', NULL, 'Dead Bug', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0199', NULL, 'Bird Dog', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0200', NULL, 'Hollow Body Hold', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0201', NULL, 'Mountain Climbers', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0202', NULL, 'V-Ups', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0203', NULL, 'Russian Twist', 'Abdomen / Core', 'ABS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0204', NULL, 'Crunch lateral', 'Oblicuos', 'OBLIQUES', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0205', NULL, 'Woodchopper en polea', 'Oblicuos', 'OBLIQUES', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0206', NULL, 'Woodchopper alto', 'Oblicuos', 'OBLIQUES', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0207', NULL, 'Woodchopper bajo', 'Oblicuos', 'OBLIQUES', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0208', NULL, 'Inclinación lateral con mancuerna', 'Oblicuos', 'OBLIQUES', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0209', NULL, 'Inclinación lateral en polea', 'Oblicuos', 'OBLIQUES', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0210', NULL, 'Plancha lateral con elevación', 'Oblicuos', 'OBLIQUES', 'STRENGTH', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0211', NULL, 'Rotación de tronco en máquina', 'Oblicuos', 'OBLIQUES', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0212', NULL, 'Encogimientos con barra', 'Trapecio', 'TRAPS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0213', NULL, 'Encogimientos con mancuernas', 'Trapecio', 'TRAPS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0214', NULL, 'Encogimientos en máquina', 'Trapecio', 'TRAPS', 'STRENGTH', 'Máquina', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0215', NULL, 'Encogimientos en Smith', 'Trapecio', 'TRAPS', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0216', NULL, 'Farmer Walk', 'Trapecio', 'TRAPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0217', NULL, 'High Pull', 'Trapecio', 'TRAPS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0218', NULL, 'Curl de muñeca', 'Antebrazos', 'FOREARMS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0219', NULL, 'Curl inverso de muñeca', 'Antebrazos', 'FOREARMS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0220', NULL, 'Curl de muñeca con barra', 'Antebrazos', 'FOREARMS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0221', NULL, 'Curl inverso con barra', 'Antebrazos', 'FOREARMS', 'STRENGTH', 'Barra', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0222', NULL, 'Hold con mancuernas', 'Antebrazos', 'FOREARMS', 'STRENGTH', 'Mancuernas', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0223', NULL, 'Pinch Grip', 'Antebrazos', 'FOREARMS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0224', NULL, 'Wrist Roller', 'Antebrazos', 'FOREARMS', 'STRENGTH', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0225', NULL, 'Caminata', 'Cardio - Caminadora', 'CARDIO', 'CARDIO', 'Caminadora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0226', NULL, 'Caminata inclinada', 'Cardio - Caminadora', 'CARDIO', 'CARDIO', 'Caminadora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0227', NULL, 'Caminata rápida', 'Cardio - Caminadora', 'CARDIO', 'CARDIO', 'Caminadora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0228', NULL, 'Trote', 'Cardio - Caminadora', 'CARDIO', 'CARDIO', 'Caminadora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0229', NULL, 'Carrera', 'Cardio - Caminadora', 'CARDIO', 'CARDIO', 'Caminadora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0230', NULL, 'Intervalos caminata/carrera', 'Cardio - Caminadora', 'CARDIO', 'CARDIO', 'Caminadora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0231', NULL, 'Sprint', 'Cardio - Caminadora', 'CARDIO', 'CARDIO', 'Caminadora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0232', NULL, 'HIIT en caminadora', 'Cardio - Caminadora', 'CARDIO', 'CARDIO', 'Caminadora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0233', NULL, 'Pedaleo suave', 'Cardio - Bicicleta', 'CARDIO', 'CARDIO', 'Bicicleta', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0234', NULL, 'Pedaleo moderado', 'Cardio - Bicicleta', 'CARDIO', 'CARDIO', 'Bicicleta', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0235', NULL, 'Pedaleo intenso', 'Cardio - Bicicleta', 'CARDIO', 'CARDIO', 'Bicicleta', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0236', NULL, 'Intervalos', 'Cardio - Bicicleta', 'CARDIO', 'CARDIO', 'Bicicleta', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0237', NULL, 'HIIT en bicicleta', 'Cardio - Bicicleta', 'CARDIO', 'CARDIO', 'Bicicleta', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0238', NULL, 'Spinning', 'Cardio - Bicicleta', 'CARDIO', 'CARDIO', 'Bicicleta', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0239', NULL, 'Escaladora continua', 'Cardio - Escaladora', 'CARDIO', 'CARDIO', 'Escaladora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0240', NULL, 'Escaladora moderada', 'Cardio - Escaladora', 'CARDIO', 'CARDIO', 'Escaladora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0241', NULL, 'Escaladora intensa', 'Cardio - Escaladora', 'CARDIO', 'CARDIO', 'Escaladora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0242', NULL, 'HIIT en escaladora', 'Cardio - Escaladora', 'CARDIO', 'CARDIO', 'Escaladora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0243', NULL, 'Escaladora lateral', 'Cardio - Escaladora', 'CARDIO', 'CARDIO', 'Escaladora', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0244', NULL, 'Remo ergómetro', 'Cardio - Remo', 'CARDIO', 'CARDIO', 'Remo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0245', NULL, 'Remo moderado', 'Cardio - Remo', 'CARDIO', 'CARDIO', 'Remo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0246', NULL, 'Remo intenso', 'Cardio - Remo', 'CARDIO', 'CARDIO', 'Remo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0247', NULL, 'HIIT en remo', 'Cardio - Remo', 'CARDIO', 'CARDIO', 'Remo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0248', NULL, 'Battle Rope', 'Cuerdas / Battle Rope', 'FULL_BODY', 'CARDIO', 'Battle Rope', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0249', NULL, 'Ondas alternadas', 'Cuerdas / Battle Rope', 'FULL_BODY', 'CARDIO', 'Battle Rope', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0250', NULL, 'Ondas simultáneas', 'Cuerdas / Battle Rope', 'FULL_BODY', 'CARDIO', 'Battle Rope', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0251', NULL, 'Golpes al suelo', 'Cuerdas / Battle Rope', 'FULL_BODY', 'CARDIO', 'Battle Rope', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0252', NULL, 'Círculos con cuerda', 'Cuerdas / Battle Rope', 'FULL_BODY', 'CARDIO', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0253', NULL, 'Battle Rope lateral', 'Cuerdas / Battle Rope', 'FULL_BODY', 'CARDIO', 'Battle Rope', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0254', NULL, 'Battle Rope + sentadilla', 'Cuerdas / Battle Rope', 'FULL_BODY', 'CARDIO', 'Battle Rope', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0255', NULL, 'Battle Rope + zancada', 'Cuerdas / Battle Rope', 'FULL_BODY', 'CARDIO', 'Battle Rope', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0256', NULL, 'Lanzamiento de balón al suelo', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0257', NULL, 'Lanzamiento contra pared', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0258', NULL, 'Lanzamiento por encima de la cabeza', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0259', NULL, 'Pase de pecho', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0260', NULL, 'Rotación con balón', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0261', NULL, 'Russian Twist con balón', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0262', NULL, 'Sentadilla con balón', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0263', NULL, 'Zancada con balón', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0264', NULL, 'Slam Ball', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0265', NULL, 'Woodchopper con balón', 'Balón medicinal', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0266', NULL, 'Salto vertical', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0267', NULL, 'Salto al cajón', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Caja pliométrica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0268', NULL, 'Box Jump', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Caja pliométrica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0269', NULL, 'Jump Squat', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0270', NULL, 'Salto largo', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0271', NULL, 'Saltos laterales', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0272', NULL, 'Skater Jump', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0273', NULL, 'Tuck Jump', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0274', NULL, 'Burpees', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0275', NULL, 'Burpee con salto', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0276', NULL, 'Saltos de tijera', 'Pliometría', 'FULL_BODY', 'PLYOMETRIC', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0277', NULL, 'Estiramiento de cuádriceps', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0278', NULL, 'Estiramiento de femoral', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0279', NULL, 'Estiramiento de glúteos', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0280', NULL, 'Estiramiento de pantorrillas', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0281', NULL, 'Estiramiento de pectoral', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0282', NULL, 'Estiramiento de dorsal', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0283', NULL, 'Estiramiento de hombros', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0284', NULL, 'Estiramiento de tríceps', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0285', NULL, 'Estiramiento de cadera', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0286', NULL, 'Rotación torácica', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0287', NULL, 'Cat-Cow', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0288', NULL, 'Child''s Pose', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0289', NULL, 'Cobra', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0290', NULL, 'Hip 90/90', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0291', NULL, 'World''s Greatest Stretch', 'Movilidad y flexibilidad', 'FULL_BODY', 'MOBILITY', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0292', NULL, 'Kettlebell Swing', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0293', NULL, 'Kettlebell Goblet Squat', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0294', NULL, 'Kettlebell Clean', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0295', NULL, 'Kettlebell Snatch', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0296', NULL, 'Kettlebell Press', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0297', NULL, 'Kettlebell Row', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0298', NULL, 'Kettlebell Deadlift', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0299', NULL, 'Kettlebell Lunge', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0300', NULL, 'Kettlebell Turkish Get-Up', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0301', NULL, 'Kettlebell Farmer Walk', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0302', NULL, 'Kettlebell High Pull', 'Kettlebell', 'FULL_BODY', 'FUNCTIONAL', 'Kettlebell', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0303', NULL, 'Press de pecho con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0304', NULL, 'Remo con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0305', NULL, 'Jalón con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0306', NULL, 'Curl de bíceps con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0307', NULL, 'Extensión de tríceps con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0308', NULL, 'Elevación lateral con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0309', NULL, 'Elevación frontal con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0310', NULL, 'Sentadilla con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0311', NULL, 'Caminata lateral con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0312', NULL, 'Glute Bridge con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0313', NULL, 'Patada de glúteo con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0314', NULL, 'Abducción con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0315', NULL, 'Pull Apart', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0316', NULL, 'Face Pull con banda', 'Bandas elásticas', 'FULL_BODY', 'STRENGTH', 'Banda elástica', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0317', NULL, 'Sentadilla', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0318', NULL, 'Sentadilla isométrica', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0319', NULL, 'Zancada', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0320', NULL, 'Zancada lateral', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0321', NULL, 'Zancada inversa', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0322', NULL, 'Fondos', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0323', NULL, 'Bear Crawl', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0324', NULL, 'Crab Walk', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0325', NULL, 'Inchworm', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0326', NULL, 'Bear Plank', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0327', NULL, 'Handstand Hold', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0328', NULL, 'Pike Push Up', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0329', NULL, 'Pistol Squat', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0330', NULL, 'Wall Sit', 'Peso corporal / Funcional', 'FULL_BODY', 'FUNCTIONAL', 'Peso corporal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0331', NULL, 'Sled Push', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Trineo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0332', NULL, 'Sled Pull', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Trineo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0333', NULL, 'Sandbag Carry', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0334', NULL, 'Sandbag Squat', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0335', NULL, 'Sandbag Clean', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0336', NULL, 'Medicine Ball Slam', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0337', NULL, 'Medicine Ball Throw', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Balón medicinal', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0338', NULL, 'Turkish Get-Up', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0339', NULL, 'Circuito funcional', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0340', NULL, 'Circuito metabólico', 'Entrenamiento funcional', 'FULL_BODY', 'FUNCTIONAL', 'Otro', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0341', NULL, 'Empuje de trineo', 'Trineo / Sled', 'FULL_BODY', 'FUNCTIONAL', 'Trineo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0342', NULL, 'Arrastre de trineo', 'Trineo / Sled', 'FULL_BODY', 'FUNCTIONAL', 'Trineo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0343', NULL, 'Empuje pesado', 'Trineo / Sled', 'FULL_BODY', 'FUNCTIONAL', 'Trineo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0344', NULL, 'Empuje ligero', 'Trineo / Sled', 'FULL_BODY', 'FUNCTIONAL', 'Trineo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0345', NULL, 'Arrastre hacia atrás', 'Trineo / Sled', 'FULL_BODY', 'FUNCTIONAL', 'Trineo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0346', NULL, 'Arrastre con cuerda', 'Trineo / Sled', 'FULL_BODY', 'FUNCTIONAL', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0347', NULL, 'Sled Sprint', 'Trineo / Sled', 'FULL_BODY', 'FUNCTIONAL', 'Trineo', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0348', NULL, 'Sentadilla en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0349', NULL, 'Sentadilla frontal en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0350', NULL, 'Hip Thrust en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0351', NULL, 'Press de banca en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0352', NULL, 'Press inclinado en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0353', NULL, 'Press de hombros en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0354', NULL, 'Remo en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0355', NULL, 'Zancada en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0356', NULL, 'Bulgarian Split Squat en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0357', NULL, 'Elevación de talones en Smith', 'Smith Machine', 'OTHER', 'STRENGTH', 'Smith Machine', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0358', NULL, 'Press de pecho', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0359', NULL, 'Cruce de poleas', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0360', NULL, 'Aperturas', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0361', NULL, 'Remo', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0362', NULL, 'Jalón', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0363', NULL, 'Pullover', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0364', NULL, 'Curl de bíceps', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0365', NULL, 'Extensión de tríceps', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0366', NULL, 'Extensión sobre cabeza', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0367', NULL, 'Elevación lateral', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0368', NULL, 'Elevación frontal', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0369', NULL, 'Patada de glúteo', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0370', NULL, 'Abducción', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0371', NULL, 'Aducción', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0372', NULL, 'Woodchopper', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE'),
('exercise_glob_0373', NULL, 'Rotación de torso', 'Poleas / Cable Crossover', 'OTHER', 'STRENGTH', 'Polea', 'INTERMEDIATE', 'ACTIVE');
