package com.astrimgym.cliente.ui.home

import java.time.LocalDate

/**
 * 365 días — Mentalidad de gladiador.
 * Un mensaje por día del año. El día 1 corresponde al 1 de enero (dayOfYear = 1).
 */
private val DAILY_MESSAGES: List<String> = listOf(
    "Hoy no vienes a entrenar. Vienes a demostrar de qué estás hecho.",
    "El hierro no perdona excusas. Levántalo.",
    "Cada repetición es una batalla. Gana la de hoy.",
    "Los guerreros no esperan motivación. Construyen disciplina.",
    "Tu cuerpo seguirá a tu mente. Haz que tu mente sea invencible.",
    "Cuando quieras detenerte, recuerda por qué comenzaste.",
    "No necesitas ser el más fuerte. Necesitas negarte a rendirte.",
    "Entra como un guerrero. Entrena como un gladiador. Sal como un vencedor.",
    "El dolor de hoy es parte de la fuerza de mañana.",
    "Nadie construye un cuerpo de acero con una voluntad de cristal.",
    "Hoy el hierro será tu enemigo. Hazlo tuyo.",
    "La disciplina aparece cuando la motivación desaparece.",
    "Cada serie te acerca a la versión que quieres ser.",
    "Los débiles buscan razones. Los guerreros buscan resultados.",
    "Tu única competencia es la persona que eras ayer.",
    "No retrocedas ante el peso. Haz que el peso retroceda ante ti.",
    "Entrena en silencio. Deja que tus resultados hagan ruido.",
    "El cansancio habla. Tu disciplina decide.",
    "Hoy no importa cuánto puedas. Importa cuánto estás dispuesto a luchar.",
    "El guerrero que llevas dentro se construye repetición tras repetición.",
    "No abandones una batalla solo porque sea difícil.",
    "El hierro transforma cuerpos, pero la disciplina transforma vidas.",
    "Cada gota de sudor es un ladrillo más en tu fortaleza.",
    "No esperes sentirte preparado. Entra y pelea.",
    "Tu límite puede estar en tu cabeza. Rompe esa barrera.",
    "Hoy tienes una misión: ser más fuerte que ayer.",
    "El gimnasio no es un lugar para esconder debilidades. Es donde las destruyes.",
    "Los campeones también se cansan. La diferencia es que continúan.",
    "Que el peso sea pesado. Que tu voluntad sea más pesada.",
    "Treinta días de disciplina pueden cambiar el rumbo de tu vida.",
    "No entrenes para impresionar. Entrena para evolucionar.",
    "La batalla empieza antes de tocar la primera pesa.",
    "Si tu mente dice «terminé», demuestra que todavía queda una repetición.",
    "La grandeza se construye cuando nadie está mirando.",
    "Hoy el único enemigo eres tus propias excusas.",
    "El cuerpo que deseas exige la disciplina que todavía estás construyendo.",
    "No hay gloria sin sacrificio.",
    "Cada entrenamiento es una oportunidad para forjar carácter.",
    "Levanta el hierro. Domina la mente. Construye al guerrero.",
    "No huyas del esfuerzo. Corre hacia él.",
    "Cuando el cuerpo pida descanso, escucha primero a tu propósito.",
    "Los guerreros no nacen fuertes. Se forjan bajo presión.",
    "Tu transformación comienza cuando dejas de negociar con tus excusas.",
    "Una repetición más puede ser la diferencia entre querer y conseguir.",
    "Hoy no buscas comodidad. Buscas crecimiento.",
    "El sudor es el precio de entrada a una versión más fuerte de ti.",
    "La batalla de hoy no puede ser peleada mañana.",
    "Ponte la armadura. Hoy toca entrenar.",
    "La constancia vence donde la motivación abandona.",
    "Cincuenta días. No has llegado hasta aquí para rendirte ahora.",
    "Haz que cada serie cuente.",
    "El hierro te pregunta una sola cosa: ¿cuánto quieres realmente cambiar?",
    "No busques el camino fácil. Busca convertirte en alguien capaz de recorrer el difícil.",
    "La fuerza se construye cuando decides continuar.",
    "Tu futuro cuerpo está esperando las decisiones que tomes hoy.",
    "No necesitas permiso para convertirte en una bestia.",
    "Entrena con hambre de progreso.",
    "Cada entrenamiento que completas es una victoria contra tu antigua versión.",
    "Que tu disciplina sea más fuerte que tu cansancio.",
    "Sesenta días de lucha. Sesenta días de construcción.",
    "El gladiador no pregunta si será difícil. Se prepara para soportarlo.",
    "Tu fuerza comienza donde terminan tus excusas.",
    "No cuentes los días. Haz que los días cuenten.",
    "El sacrificio de hoy será la confianza de mañana.",
    "La barra no sabe quién eres. Demuéstrale lo que puedes hacer.",
    "Entrena como si tu yo del futuro estuviera observándote.",
    "El progreso lento sigue siendo progreso. No te detengas.",
    "Cada repetición es un golpe contra tus límites.",
    "No viniste a sobrevivir el entrenamiento. Viniste a dominarlo.",
    "Setenta días. La disciplina ya está empezando a convertirse en carácter.",
    "Cuando otros descansan, tú puedes estar construyendo la diferencia.",
    "La grandeza exige hacer lo que otros no quieren hacer.",
    "Tu cuerpo escucha cada decisión que tomas.",
    "El dolor pasa. El orgullo de no haberte rendido permanece.",
    "Hoy escribe otra página de tu transformación.",
    "No importa cómo comenzaste. Importa cómo decides continuar.",
    "Un guerrero no necesita espectadores para luchar.",
    "El entrenamiento de hoy es el físico que mañana agradecerás.",
    "La voluntad se fortalece igual que un músculo: usándola.",
    "Ochenta días. Sigue forjando tu armadura.",
    "El hierro no se levanta solo. Tampoco tus sueños.",
    "No permitas que un mal día destruya una gran disciplina.",
    "Entrena aunque no tengas ganas. Ahí vive la verdadera disciplina.",
    "Tu potencial no sirve de nada si no lo trabajas.",
    "Cada gota de sudor cuenta.",
    "El guerrero acepta el esfuerzo porque conoce la recompensa.",
    "Haz hoy algo que tu yo de ayer no pudo hacer.",
    "No busques excusas para bajar el peso. Busca razones para subirlo.",
    "El carácter aparece cuando aparece el cansancio.",
    "Noventa días. Tres meses de guerra contra tus límites.",
    "No estás construyendo músculos. Estás construyendo disciplina.",
    "Tu transformación no necesita aplausos.",
    "El entrenamiento comienza cuando la comodidad termina.",
    "La fuerza se gana una repetición a la vez.",
    "Hoy tienes otra batalla. No la desperdicies.",
    "No seas esclavo de tu comodidad.",
    "Domina tu cuerpo antes de pedirle que sea fuerte.",
    "El sudor de hoy es la armadura de mañana.",
    "Mañana agradecerás haber terminado la serie que hoy querías abandonar.",
    "Cien días. Ya no eres quien comenzó. Sigue.",
    "La disciplina convierte pequeños esfuerzos en grandes cambios.",
    "El hierro revela tu carácter.",
    "No necesitas suerte. Necesitas consistencia.",
    "Hoy entrena con propósito.",
    "Un guerrero no negocia con la debilidad.",
    "El camino difícil está construyendo una versión difícil de derrotar.",
    "Tu esfuerzo silencioso algún día será imposible de ignorar.",
    "Haz que cada serie tenga intención.",
    "No te detengas porque duela. Detente cuando hayas cumplido.",
    "Ciento diez días de disciplina. La batalla continúa.",
    "No busques sentirte fuerte. Trabaja hasta serlo.",
    "Tu cuerpo es el templo. Tu disciplina es la guardia.",
    "La comodidad nunca construyó leyendas.",
    "Hoy toca pagar el precio del progreso.",
    "La constancia convierte esfuerzo en resultados.",
    "El guerrero no teme al peso. Respeta el desafío.",
    "Una mala sesión no destruye tu progreso. Abandonar sí.",
    "Entrena para que tus límites tengan miedo de ti.",
    "Hoy vuelve a demostrarte quién manda.",
    "Ciento veinte días. La disciplina ya forma parte de tu identidad.",
    "No necesitas motivación cuando tienes una misión.",
    "Cada serie es una oportunidad para vencerte.",
    "El cuerpo cambia cuando la mente deja de buscar excusas.",
    "El esfuerzo no es castigo. Es construcción.",
    "Hoy forja algo que mañana no pueda romperse.",
    "Los guerreros no buscan caminos sin obstáculos.",
    "La repetición que cuesta es la que más te transforma.",
    "Haz que tu disciplina sea innegociable.",
    "Entrena con fuego en la mente y control en el cuerpo.",
    "Ciento treinta días. Todavía queda guerra por ganar.",
    "Tu mejor versión no aparecerá por accidente.",
    "No te preguntes si puedes. Empieza.",
    "El cansancio es temporal. La satisfacción de vencerlo permanece.",
    "Tu esfuerzo de hoy será visible algún día.",
    "El gimnasio es tu campo de batalla. Entra preparado.",
    "Haz que tus acciones sean más fuertes que tus palabras.",
    "No abandones porque no veas resultados todavía.",
    "El hierro premia a quienes regresan.",
    "Hoy puedes ser más fuerte. Hazlo.",
    "Ciento cuarenta días. Sigue marchando.",
    "La disciplina no pregunta cómo te sientes.",
    "Tu enemigo no es el peso. Es la duda.",
    "Cada entrenamiento fortalece algo más que tus músculos.",
    "Hoy entrena con la determinación de alguien que no piensa rendirse.",
    "Los resultados son la sombra de tus hábitos.",
    "Tu voluntad también necesita entrenamiento.",
    "Siete días más. Otra batalla ganada.",
    "El cuerpo que quieres exige acciones que todavía no haces.",
    "No permitas que el cansancio decida tu destino.",
    "Ciento cincuenta días. Mitad del camino. La guerra continúa.",
    "La fuerza no se regala. Se conquista.",
    "Entrena como si cada repetición tuviera un propósito.",
    "El guerrero respeta el proceso.",
    "Hoy tienes la oportunidad de superar otro límite.",
    "No busques perfección. Busca progreso.",
    "La disciplina convierte días normales en transformaciones extraordinarias.",
    "No abandones una guerra por perder una batalla.",
    "El hierro espera. ¿Tú estás listo?",
    "Haz que hoy sea otro día que puedas recordar con orgullo.",
    "Ciento sesenta días. Tu constancia empieza a hablar por ti.",
    "No necesitas ser invencible. Necesitas levantarte cada vez que caigas.",
    "El sudor es evidencia de que estuviste dispuesto a luchar.",
    "Tu cuerpo será el resultado de tus decisiones repetidas.",
    "Hoy no entrenes a medias.",
    "El gladiador entra al coliseo sabiendo que habrá dolor.",
    "No huyas de la dificultad. Úsala.",
    "Tu límite de hoy puede ser tu calentamiento de mañana.",
    "La fuerza comienza con una decisión.",
    "El entrenamiento que casi abandonas puede ser el que más recuerdes.",
    "Ciento setenta días. Mantén la espada levantada.",
    "El camino sigue. Tú también.",
    "Tu disciplina debe sobrevivir incluso a tus malos días.",
    "No entrenes para demostrar que eres fuerte. Entrena para volverte fuerte.",
    "Cada repetición es una pequeña victoria.",
    "El guerrero no espera condiciones perfectas.",
    "Hoy es otro día para construir carácter.",
    "Tu transformación se encuentra detrás de la constancia.",
    "El esfuerzo de hoy no necesita explicación.",
    "Deja que el entrenamiento hable.",
    "Ciento ochenta días. Medio año de batalla.",
    "Si quieres resultados diferentes, lucha de manera diferente.",
    "El músculo crece con estímulo. El carácter crece con disciplina.",
    "No permitas que una excusa sea más fuerte que tu objetivo.",
    "Hoy vuelve a entrar al campo.",
    "La victoria comienza con presentarte.",
    "Haz lo difícil mientras otros buscan comodidad.",
    "Tu fuerza futura depende de tu disciplina presente.",
    "El hierro no juzga. Solo responde al esfuerzo.",
    "No cuentes las repeticiones. Haz que cada una cuente.",
    "Ciento noventa días. Sigues aquí porque decidiste luchar.",
    "El guerrero no necesita una razón nueva cada día. Tiene una misión.",
    "Entrena con paciencia. Construye con disciplina.",
    "El progreso no siempre se ve, pero siempre se construye.",
    "Hoy vence la versión de ti que quería quedarse en casa.",
    "El esfuerzo repetido se convierte en transformación.",
    "No temas al fracaso. Teme dejar de intentarlo.",
    "Tu próxima repetición puede cambiar tu día.",
    "Levanta con control. Lucha con determinación.",
    "Mañana comienza con lo que haces hoy.",
    "Doscientos días. Ya construiste una historia. Ahora construye una leyenda.",
    "El cuerpo fuerte nace de hábitos fuertes.",
    "No permitas que el cansancio robe tu propósito.",
    "Hoy tienes otra oportunidad de superar tus límites.",
    "La disciplina es hacer lo correcto incluso cuando nadie te obliga.",
    "Tu enemigo favorito debería ser tu antiguo yo.",
    "Entrena con hambre, pero con inteligencia.",
    "El esfuerzo sin constancia es solo un momento.",
    "La constancia convierte momentos en resultados.",
    "Hoy toca otra batalla. Preséntate.",
    "Doscientos diez días. El guerrero sigue de pie.",
    "No necesitas que sea fácil. Necesitas que valga la pena.",
    "Tu disciplina es tu arma.",
    "El gimnasio no cambia tu vida. Tus decisiones dentro de él sí.",
    "Entrena con respeto por el proceso.",
    "El sacrificio que nadie ve construye los resultados que todos ven.",
    "Cada gota de sudor lleva tu firma.",
    "No te rindas en medio de la construcción.",
    "Hoy vuelve a levantar tu estándar.",
    "La grandeza se encuentra en las pequeñas decisiones repetidas.",
    "Doscientos veinte días. Sigue avanzando.",
    "No necesitas compararte. Necesitas superarte.",
    "El guerrero sabe cuándo empujar y cuándo recuperarse.",
    "La disciplina también es respetar tu descanso.",
    "Entrena duro, recupera mejor, vuelve más fuerte.",
    "Tu cuerpo necesita esfuerzo. Tu mente necesita propósito.",
    "Hoy construyes algo que nadie puede regalarte.",
    "La batalla no siempre se gana con fuerza. También con paciencia.",
    "No aceleres el proceso. Domínalo.",
    "Haz de la constancia tu ventaja secreta.",
    "Doscientos treinta días. La armadura sigue fortaleciéndose.",
    "El guerrero no abandona porque el camino sea largo.",
    "Cada entrenamiento es un voto por la persona que quieres ser.",
    "Hoy vota por tu mejor versión.",
    "No necesitas aplausos para saber que estás progresando.",
    "La fuerza aparece después de la decisión de esforzarte.",
    "Tu disciplina será más importante que tu talento.",
    "Haz que la comodidad te extrañe.",
    "El hierro espera a los constantes.",
    "No abandones el camino justo antes de descubrir hasta dónde puedes llegar.",
    "Doscientos cuarenta días. Todavía puedes subir el nivel.",
    "Hoy entrena como alguien que tiene algo que demostrarle a sí mismo.",
    "Tu mejor arma no es la fuerza. Es la constancia.",
    "El guerrero acepta que algunas batallas serán difíciles.",
    "No necesitas ganar todos los días. Necesitas seguir luchando.",
    "Tu progreso merece paciencia.",
    "El cuerpo cambia lentamente. La disciplina cambia inmediatamente.",
    "Hoy tienes otra oportunidad de ser mejor.",
    "No desperdicies un día que podría acercarte a tu objetivo.",
    "El cansancio no define tu fuerza. Tu decisión de continuar sí.",
    "Doscientos cincuenta días. La batalla te ha hecho más fuerte.",
    "El guerrero no espera condiciones perfectas.",
    "Haz hoy lo que otros posponen.",
    "La disciplina convierte intención en acción.",
    "Tu cuerpo recuerda cada batalla que decidiste enfrentar.",
    "El esfuerzo de hoy será parte de tu historia mañana.",
    "No tengas miedo de empezar otra vez. Los guerreros también reconstruyen.",
    "Una repetición más. Una decisión más. Un paso más.",
    "No necesitas correr. Solo necesitas no detenerte.",
    "El camino hacia la fuerza pasa por días difíciles.",
    "Doscientos sesenta días. Sigue forjándote.",
    "Tu disciplina habla cuando tus palabras callan.",
    "Entrena con propósito, no con prisa.",
    "La fuerza sin control no es fuerza.",
    "Aprende a dominar el peso y también tu mente.",
    "Hoy construyes confianza con acciones.",
    "El guerrero no teme empezar pequeño.",
    "Grandes cuerpos se construyen con pequeños hábitos.",
    "No subestimes el poder de presentarte cada día.",
    "Tu constancia puede llevarte donde tu talento no pudo.",
    "Doscientos setenta días. Nueve meses de disciplina.",
    "No necesitas ser perfecto. Necesitas ser constante.",
    "Cada entrenamiento es una inversión en ti.",
    "Hoy invierte en tu futuro.",
    "La batalla termina cuando decides dejar de luchar.",
    "Mantente firme.",
    "Tu objetivo no se construirá solo.",
    "El hierro es pesado. Tus razones deben ser más fuertes.",
    "No permitas que un mal momento defina tu camino.",
    "Regresa al campo y continúa.",
    "Doscientos ochenta días. Has sobrevivido a cientos de excusas.",
    "Hoy no necesitas motivación. Necesitas acción.",
    "Tu mejor versión está detrás de otra serie.",
    "La disciplina es la diferencia entre querer y hacer.",
    "Entrena con la mente fría y el corazón encendido.",
    "El guerrero conoce su objetivo y respeta su proceso.",
    "No persigas resultados rápidos. Persigue resultados duraderos.",
    "Cada día de disciplina fortalece tu identidad.",
    "El cuerpo que sueñas empieza con el entrenamiento que haces hoy.",
    "No abandones porque el progreso sea lento.",
    "Doscientos noventa días. El hierro te conoce.",
    "Sigue levantando.",
    "Sigue luchando.",
    "Sigue construyendo.",
    "Sigue creyendo en el proceso.",
    "No estás aquí por casualidad. Estás aquí por decisión.",
    "La fuerza nace de la repetición.",
    "La disciplina nace de cumplirte tus propias promesas.",
    "Hoy cumple otra.",
    "Mañana recordarás este esfuerzo con orgullo.",
    "Trescientos días. Ya no estás persiguiendo una transformación. Estás viviendo una.",
    "El guerrero continúa incluso cuando la novedad desaparece.",
    "La verdadera disciplina aparece después de los primeros cien días.",
    "No bajes la guardia.",
    "Tu progreso necesita continuidad.",
    "Entrena hoy para agradecerte mañana.",
    "El esfuerzo constante supera al entusiasmo pasajero.",
    "Tu voluntad puede ser más fuerte que tu cansancio.",
    "El gimnasio es donde conviertes intención en evidencia.",
    "Que tus acciones sean dignas de tus objetivos.",
    "Trescientos diez días. El guerrero permanece.",
    "No necesitas demostrar nada a nadie. Demuéstratelo a ti.",
    "El peso puede desafiarte. No puede decidir por ti.",
    "Hoy tienes otra oportunidad de crecer.",
    "La constancia hace extraordinario lo ordinario.",
    "Sigue adelante aunque nadie vea tu esfuerzo.",
    "Las mejores batallas son las que te convierten en alguien mejor.",
    "Entrena con inteligencia. Lucha con disciplina.",
    "Tu cuerpo necesita tiempo. Dale también constancia.",
    "No abandones tu misión.",
    "Trescientos veinte días. La espada sigue levantada.",
    "Tu fuerza no está terminada. Sigue construyéndola.",
    "No busques excusas. Busca progreso.",
    "Cada entrenamiento es una declaración: no me rindo.",
    "La disciplina convierte esfuerzo en identidad.",
    "El guerrero respeta cada etapa de su evolución.",
    "Hoy lucha contra la comodidad.",
    "Haz que tu futuro yo esté orgulloso de tu decisión de hoy.",
    "La transformación requiere paciencia y fuego.",
    "Mantén el fuego encendido.",
    "Trescientos treinta días. Has llegado demasiado lejos para detenerte.",
    "El hierro es una herramienta. Tu mente es el arma.",
    "Domina ambas.",
    "Hoy vuelve a demostrar tu compromiso.",
    "La fuerza no llega cuando la esperas. Llega cuando la construyes.",
    "No hay transformación sin incomodidad.",
    "Acepta el esfuerzo. Abraza el proceso.",
    "El guerrero no busca comodidad. Busca evolución.",
    "Cada repetición deja una marca.",
    "Haz que esa marca represente disciplina.",
    "Trescientos cuarenta días. Tu historia aún no termina.",
    "Entrena como si todavía tuvieras algo que demostrar.",
    "Porque siempre puedes superar a quien eras ayer.",
    "El verdadero rival vive dentro del espejo.",
    "Véncelo con acciones.",
    "Tu cuerpo es el resultado de cientos de decisiones pequeñas.",
    "Hoy toma otra buena decisión.",
    "La batalla de hoy merece tu mejor esfuerzo.",
    "No importa cuántas veces hayas caído. Importa cuántas veces te levantaste.",
    "Sigue de pie.",
    "Trescientos cincuenta días. Diez meses de guerra contra tus límites.",
    "Ya conoces el camino. Ahora camínalo con más fuerza.",
    "El guerrero no necesita una nueva razón. Tiene una promesa.",
    "Cumple la promesa que hiciste cuando comenzaste.",
    "Hoy vuelve a luchar por ti.",
    "La fuerza que buscas está detrás de la disciplina que evitas.",
    "No retrocedas.",
    "No bajes el ritmo.",
    "No apagues el fuego.",
    "Estás a pocos pasos de completar otra batalla.",
    "Trescientos sesenta días. El guerrero que comenzó ya no existe.",
    "Quedan cinco días. Termina con honor.",
    "Quedan cuatro días. Levanta la cabeza y sigue.",
    "Quedan tres días. La batalla aún no termina.",
    "Un día más. Una última batalla antes de comenzar otra.",
    "Terminaste un año de batallas. Pero un verdadero guerrero no termina: vuelve a levantarse mañana y comienza de nuevo.",
)

/** Número de día (1–365) que corresponde a la fecha de hoy. */
fun dailyMessageDayNumber(today: LocalDate = LocalDate.now()): Int =
    (today.dayOfYear - 1) % DAILY_MESSAGES.size + 1

/** Mensaje de mentalidad de gladiador para el día de hoy. */
fun messageOfTheDay(today: LocalDate = LocalDate.now()): String =
    DAILY_MESSAGES[(today.dayOfYear - 1) % DAILY_MESSAGES.size]
